### ISSUE TITLE
The following error occurs in the runtime, how to solve it? I am not very familiar with tensorflow

### ISSUE THREAD

**Issue by outman-goutian** [wilkinghoff/dcase2022#2]
![image](https://user-images.githubusercontent.com/62677747/187074028-405192e0-0fc4-4c8c-920f-a8eb53a5755d.png)

Loading train data
Loading evaluation data
Loading test data
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
[<ipython-input-25-49023814459f>](https://localhost:8080/#) in <module>
    415     # compile model
    416     data_input, label_input, loss_output = model_emb_cnn(num_classes=num_classes_4train,
--> 417                                                              raw_dim=eval_raw.shape[1], n_subclusters=n_subclusters)
    418     model = tf.keras.Model(inputs=[data_input, label_input], outputs=[loss_output])
    419     model.compile(loss=[mixupLoss], optimizer=tf.keras.optimizers.Adam())

2 frames
[<ipython-input-25-49023814459f>](https://localhost:8080/#) in model_emb_cnn(num_classes, raw_dim, n_subclusters)
    118     x = data_input
    119     l2_weight_decay = tf.keras.regularizers.l2(1e-5)
--> 120     x_mix, y = MixupLayer(prob=1)([x, y])
    121 
    122     # FFT

[/usr/local/lib/python3.7/dist-packages/keras/utils/traceback_utils.py](https://localhost:8080/#) in error_handler(*args, **kwargs)
     65     except Exception as e:  # pylint: disable=broad-except
     66       filtered_tb = _process_traceback_frames(e.__traceback__)
---> 67       raise e.with_traceback(filtered_tb) from None
     68     finally:
     69       del filtered_tb

[/usr/local/lib/python3.7/dist-packages/tensorflow/python/autograph/impl/api.py](https://localhost:8080/#) in wrapper(*args, **kwargs)
    690       except Exception as e:  # pylint:disable=broad-except
    691         if hasattr(e, 'ag_error_metadata'):
--> 692           raise e.ag_error_metadata.to_exception(e)
    693         else:
    694           raise

TypeError: Exception encountered when calling layer "mixup_layer_8" (type MixupLayer).

in user code:

    File "<ipython-input-24-b6e9be9946f0>", line 22, in call  *
        l = tf.random.uniform(shape=[tf.shape(inputs[0])[0]])

    TypeError: 'str' object is not callable

Call arguments received:
  • inputs=['tf.Tensor(shape=(None, 160000, 1), dtype=float32)', 'tf.Tensor(shape=(None, 22), dtype=float32)']
  • training=None

**Comment by wilkinghoff** [comment]
Have you tried to simply rerun the code? Sometimes I get this error when running the code for the first time and collecting all audio files into numpy arrays. I really don't know why.

**Comment by outman-goutian** [comment]
I checked many times and finally found that it was due to the version of tensorflow. The version of google colab I used was 2.8, while yours was 2.3. I was too careless.
