### ISSUE TITLE
training speed problem

### ISSUE THREAD

**Issue by outman-goutian** [wilkinghoff/dcase2022#3]
hey bro, the retraining of the model is slow, I guess it is taking a lot of time when converting the wav to logmel spectrogram, is there any workaround? In addition, in order to prevent insufficient RAM (25GB), I only put the files of two machines. If all machines are put in, how much RAM is needed?

**Comment by wilkinghoff** [comment]
Converting the wav to logmel should not take too long. You could compute the log mel spectrograms in advance but this requires additional RAM... I guess the easiest way to speed up training would be a GPU upgrade. You can also try to adjust the batch size.
I have 32 GB RAM on my machine and it is working fine.

**Comment by li19980813** [comment]
I would like to know whether your GPU size is for one machine or several?

**Comment by wilkinghoff** [comment]
I am using a NVIDIA Quadro RTX 5000 with 16GB on a laptop and can run the code as you can find it here (using all machine types).
